/*
 * This file has been generated by the onto2vocabularyclass tool
 * copyright (C) 2007-2008 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

#include "knx.h"

class KnxPrivate
{
public:
    KnxPrivate()
        : knx_namespace( QUrl::fromEncoded( "http://nepomuk.kde.org/ontologies/2008/05/07/knx#", QUrl::StrictMode ) ),
          knx_hasIcon( QUrl::fromEncoded( "http://nepomuk.kde.org/ontologies/2008/05/07/knx#hasIcon", QUrl::StrictMode ) ) {
    }

    QUrl knx_namespace;
    QUrl knx_hasIcon;
};

Q_GLOBAL_STATIC( KnxPrivate, s_knx )

QUrl Nepomuk::Vocabulary::KNX::knxNamespace()
{
    return s_knx()->knx_namespace;
}

QUrl Nepomuk::Vocabulary::KNX::hasIcon()
{
    return s_knx()->knx_hasIcon;
}
