/*
 * This file has been generated by the onto2vocabularyclass tool
 * copyright (C) 2007-2008 Sebastian Trueg <trueg@kde.org>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

#include "pimo.h"

class PimoPrivate
{
public:
    PimoPrivate()
        : pimo_namespace( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#" ),
          pimo_Agent( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Agent" ),
          pimo_Association( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Association" ),
          pimo_Attendee( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Attendee" ),
          pimo_BlogPost( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#BlogPost" ),
          pimo_Building( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Building" ),
          pimo_City( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#City" ),
          pimo_ClassOrThing( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#ClassOrThing" ),
          pimo_ClassOrThingOrPropertyOrAssociation( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#ClassOrThingOrPropertyOrAssociation" ),
          pimo_ClassRole( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#ClassRole" ),
          pimo_Collection( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Collection" ),
          pimo_Contract( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Contract" ),
          pimo_Country( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Country" ),
          pimo_Document( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Document" ),
          pimo_Event( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Event" ),
          pimo_Locatable( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Locatable" ),
          pimo_Location( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Location" ),
          pimo_LogicalMediaType( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#LogicalMediaType" ),
          pimo_Meeting( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Meeting" ),
          pimo_Organization( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Organization" ),
          pimo_OrganizationMember( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#OrganizationMember" ),
          pimo_Person( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Person" ),
          pimo_PersonGroup( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#PersonGroup" ),
          pimo_PersonRole( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#PersonRole" ),
          pimo_PersonalInformationModel( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#PersonalInformationModel" ),
          pimo_ProcessConcept( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#ProcessConcept" ),
          pimo_Project( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Project" ),
          pimo_Room( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Room" ),
          pimo_SocialEvent( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#SocialEvent" ),
          pimo_State( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#State" ),
          pimo_Task( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Task" ),
          pimo_Thing( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Thing" ),
          pimo_Topic( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Topic" ),
          pimo_associationEffectual( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#associationEffectual" ),
          pimo_associationMember( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#associationMember" ),
          pimo_attendee( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#attendee" ),
          pimo_attendingMeeting( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#attendingMeeting" ),
          pimo_attends( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#attends" ),
          pimo_classRole( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#classRole" ),
          pimo_containsLocation( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#containsLocation" ),
          pimo_createdPimo( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#createdPimo" ),
          pimo_creator( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#creator" ),
          pimo_datatypeProperty( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#datatypeProperty" ),
          pimo_dtend( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#dtend" ),
          pimo_dtstart( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#dtstart" ),
          pimo_duration( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#duration" ),
          pimo_groundingForDeletedThing( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#groundingForDeletedThing" ),
          pimo_groundingOccurrence( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#groundingOccurrence" ),
          pimo_hasDeprecatedRepresentation( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasDeprecatedRepresentation" ),
          pimo_hasFolder( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasFolder" ),
          pimo_hasLocation( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasLocation" ),
          pimo_hasOrganizationMember( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasOrganizationMember" ),
          pimo_hasOtherConceptualization( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasOtherConceptualization" ),
          pimo_hasOtherRepresentation( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasOtherRepresentation" ),
          pimo_hasOtherSlot( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasOtherSlot" ),
          pimo_hasPart( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasPart" ),
          pimo_hasTopic( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasTopic" ),
          pimo_isDefinedBy( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#isDefinedBy" ),
          pimo_isLocationOf( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#isLocationOf" ),
          pimo_isOrganizationMemberOf( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#isOrganizationMemberOf" ),
          pimo_isRelated( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#isRelated" ),
          pimo_isTopicOf( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#isTopicOf" ),
          pimo_isWriteable( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#isWriteable" ),
          pimo_locatedWithin( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#locatedWithin" ),
          pimo_objectProperty( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#objectProperty" ),
          pimo_occurrence( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#occurrence" ),
          pimo_organization( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#organization" ),
          pimo_partOf( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#partOf" ),
          pimo_referencingOccurrence( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#referencingOccurrence" ),
          pimo_roleContext( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#roleContext" ),
          pimo_roleHolder( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#roleHolder" ),
          pimo_subTopic( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#subTopic" ),
          pimo_superTopic( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#superTopic" ),
          pimo_taskDueTime( "http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#taskDueTime" ) {
    }

    QUrl pimo_namespace;
    QUrl pimo_Agent;
    QUrl pimo_Association;
    QUrl pimo_Attendee;
    QUrl pimo_BlogPost;
    QUrl pimo_Building;
    QUrl pimo_City;
    QUrl pimo_ClassOrThing;
    QUrl pimo_ClassOrThingOrPropertyOrAssociation;
    QUrl pimo_ClassRole;
    QUrl pimo_Collection;
    QUrl pimo_Contract;
    QUrl pimo_Country;
    QUrl pimo_Document;
    QUrl pimo_Event;
    QUrl pimo_Locatable;
    QUrl pimo_Location;
    QUrl pimo_LogicalMediaType;
    QUrl pimo_Meeting;
    QUrl pimo_Organization;
    QUrl pimo_OrganizationMember;
    QUrl pimo_Person;
    QUrl pimo_PersonGroup;
    QUrl pimo_PersonRole;
    QUrl pimo_PersonalInformationModel;
    QUrl pimo_ProcessConcept;
    QUrl pimo_Project;
    QUrl pimo_Room;
    QUrl pimo_SocialEvent;
    QUrl pimo_State;
    QUrl pimo_Task;
    QUrl pimo_Thing;
    QUrl pimo_Topic;
    QUrl pimo_associationEffectual;
    QUrl pimo_associationMember;
    QUrl pimo_attendee;
    QUrl pimo_attendingMeeting;
    QUrl pimo_attends;
    QUrl pimo_classRole;
    QUrl pimo_containsLocation;
    QUrl pimo_createdPimo;
    QUrl pimo_creator;
    QUrl pimo_datatypeProperty;
    QUrl pimo_dtend;
    QUrl pimo_dtstart;
    QUrl pimo_duration;
    QUrl pimo_groundingForDeletedThing;
    QUrl pimo_groundingOccurrence;
    QUrl pimo_hasDeprecatedRepresentation;
    QUrl pimo_hasFolder;
    QUrl pimo_hasLocation;
    QUrl pimo_hasOrganizationMember;
    QUrl pimo_hasOtherConceptualization;
    QUrl pimo_hasOtherRepresentation;
    QUrl pimo_hasOtherSlot;
    QUrl pimo_hasPart;
    QUrl pimo_hasTopic;
    QUrl pimo_isDefinedBy;
    QUrl pimo_isLocationOf;
    QUrl pimo_isOrganizationMemberOf;
    QUrl pimo_isRelated;
    QUrl pimo_isTopicOf;
    QUrl pimo_isWriteable;
    QUrl pimo_locatedWithin;
    QUrl pimo_objectProperty;
    QUrl pimo_occurrence;
    QUrl pimo_organization;
    QUrl pimo_partOf;
    QUrl pimo_referencingOccurrence;
    QUrl pimo_roleContext;
    QUrl pimo_roleHolder;
    QUrl pimo_subTopic;
    QUrl pimo_superTopic;
    QUrl pimo_taskDueTime;
};

Q_GLOBAL_STATIC( PimoPrivate, s_pimo )

QUrl Nepomuk::Vocabulary::PIMO::pimoNamespace()
{
    return s_pimo()->pimo_namespace;
}

QUrl Nepomuk::Vocabulary::PIMO::Agent()
{
    return s_pimo()->pimo_Agent;
}

QUrl Nepomuk::Vocabulary::PIMO::Association()
{
    return s_pimo()->pimo_Association;
}

QUrl Nepomuk::Vocabulary::PIMO::Attendee()
{
    return s_pimo()->pimo_Attendee;
}

QUrl Nepomuk::Vocabulary::PIMO::BlogPost()
{
    return s_pimo()->pimo_BlogPost;
}

QUrl Nepomuk::Vocabulary::PIMO::Building()
{
    return s_pimo()->pimo_Building;
}

QUrl Nepomuk::Vocabulary::PIMO::City()
{
    return s_pimo()->pimo_City;
}

QUrl Nepomuk::Vocabulary::PIMO::ClassOrThing()
{
    return s_pimo()->pimo_ClassOrThing;
}

QUrl Nepomuk::Vocabulary::PIMO::ClassOrThingOrPropertyOrAssociation()
{
    return s_pimo()->pimo_ClassOrThingOrPropertyOrAssociation;
}

QUrl Nepomuk::Vocabulary::PIMO::ClassRole()
{
    return s_pimo()->pimo_ClassRole;
}

QUrl Nepomuk::Vocabulary::PIMO::Collection()
{
    return s_pimo()->pimo_Collection;
}

QUrl Nepomuk::Vocabulary::PIMO::Contract()
{
    return s_pimo()->pimo_Contract;
}

QUrl Nepomuk::Vocabulary::PIMO::Country()
{
    return s_pimo()->pimo_Country;
}

QUrl Nepomuk::Vocabulary::PIMO::Document()
{
    return s_pimo()->pimo_Document;
}

QUrl Nepomuk::Vocabulary::PIMO::Event()
{
    return s_pimo()->pimo_Event;
}

QUrl Nepomuk::Vocabulary::PIMO::Locatable()
{
    return s_pimo()->pimo_Locatable;
}

QUrl Nepomuk::Vocabulary::PIMO::Location()
{
    return s_pimo()->pimo_Location;
}

QUrl Nepomuk::Vocabulary::PIMO::LogicalMediaType()
{
    return s_pimo()->pimo_LogicalMediaType;
}

QUrl Nepomuk::Vocabulary::PIMO::Meeting()
{
    return s_pimo()->pimo_Meeting;
}

QUrl Nepomuk::Vocabulary::PIMO::Organization()
{
    return s_pimo()->pimo_Organization;
}

QUrl Nepomuk::Vocabulary::PIMO::OrganizationMember()
{
    return s_pimo()->pimo_OrganizationMember;
}

QUrl Nepomuk::Vocabulary::PIMO::Person()
{
    return s_pimo()->pimo_Person;
}

QUrl Nepomuk::Vocabulary::PIMO::PersonGroup()
{
    return s_pimo()->pimo_PersonGroup;
}

QUrl Nepomuk::Vocabulary::PIMO::PersonRole()
{
    return s_pimo()->pimo_PersonRole;
}

QUrl Nepomuk::Vocabulary::PIMO::PersonalInformationModel()
{
    return s_pimo()->pimo_PersonalInformationModel;
}

QUrl Nepomuk::Vocabulary::PIMO::ProcessConcept()
{
    return s_pimo()->pimo_ProcessConcept;
}

QUrl Nepomuk::Vocabulary::PIMO::Project()
{
    return s_pimo()->pimo_Project;
}

QUrl Nepomuk::Vocabulary::PIMO::Room()
{
    return s_pimo()->pimo_Room;
}

QUrl Nepomuk::Vocabulary::PIMO::SocialEvent()
{
    return s_pimo()->pimo_SocialEvent;
}

QUrl Nepomuk::Vocabulary::PIMO::State()
{
    return s_pimo()->pimo_State;
}

QUrl Nepomuk::Vocabulary::PIMO::Task()
{
    return s_pimo()->pimo_Task;
}

QUrl Nepomuk::Vocabulary::PIMO::Thing()
{
    return s_pimo()->pimo_Thing;
}

QUrl Nepomuk::Vocabulary::PIMO::Topic()
{
    return s_pimo()->pimo_Topic;
}

QUrl Nepomuk::Vocabulary::PIMO::associationEffectual()
{
    return s_pimo()->pimo_associationEffectual;
}

QUrl Nepomuk::Vocabulary::PIMO::associationMember()
{
    return s_pimo()->pimo_associationMember;
}

QUrl Nepomuk::Vocabulary::PIMO::attendee()
{
    return s_pimo()->pimo_attendee;
}

QUrl Nepomuk::Vocabulary::PIMO::attendingMeeting()
{
    return s_pimo()->pimo_attendingMeeting;
}

QUrl Nepomuk::Vocabulary::PIMO::attends()
{
    return s_pimo()->pimo_attends;
}

QUrl Nepomuk::Vocabulary::PIMO::classRole()
{
    return s_pimo()->pimo_classRole;
}

QUrl Nepomuk::Vocabulary::PIMO::containsLocation()
{
    return s_pimo()->pimo_containsLocation;
}

QUrl Nepomuk::Vocabulary::PIMO::createdPimo()
{
    return s_pimo()->pimo_createdPimo;
}

QUrl Nepomuk::Vocabulary::PIMO::creator()
{
    return s_pimo()->pimo_creator;
}

QUrl Nepomuk::Vocabulary::PIMO::datatypeProperty()
{
    return s_pimo()->pimo_datatypeProperty;
}

QUrl Nepomuk::Vocabulary::PIMO::dtend()
{
    return s_pimo()->pimo_dtend;
}

QUrl Nepomuk::Vocabulary::PIMO::dtstart()
{
    return s_pimo()->pimo_dtstart;
}

QUrl Nepomuk::Vocabulary::PIMO::duration()
{
    return s_pimo()->pimo_duration;
}

QUrl Nepomuk::Vocabulary::PIMO::groundingForDeletedThing()
{
    return s_pimo()->pimo_groundingForDeletedThing;
}

QUrl Nepomuk::Vocabulary::PIMO::groundingOccurrence()
{
    return s_pimo()->pimo_groundingOccurrence;
}

QUrl Nepomuk::Vocabulary::PIMO::hasDeprecatedRepresentation()
{
    return s_pimo()->pimo_hasDeprecatedRepresentation;
}

QUrl Nepomuk::Vocabulary::PIMO::hasFolder()
{
    return s_pimo()->pimo_hasFolder;
}

QUrl Nepomuk::Vocabulary::PIMO::hasLocation()
{
    return s_pimo()->pimo_hasLocation;
}

QUrl Nepomuk::Vocabulary::PIMO::hasOrganizationMember()
{
    return s_pimo()->pimo_hasOrganizationMember;
}

QUrl Nepomuk::Vocabulary::PIMO::hasOtherConceptualization()
{
    return s_pimo()->pimo_hasOtherConceptualization;
}

QUrl Nepomuk::Vocabulary::PIMO::hasOtherRepresentation()
{
    return s_pimo()->pimo_hasOtherRepresentation;
}

QUrl Nepomuk::Vocabulary::PIMO::hasOtherSlot()
{
    return s_pimo()->pimo_hasOtherSlot;
}

QUrl Nepomuk::Vocabulary::PIMO::hasPart()
{
    return s_pimo()->pimo_hasPart;
}

QUrl Nepomuk::Vocabulary::PIMO::hasTopic()
{
    return s_pimo()->pimo_hasTopic;
}

QUrl Nepomuk::Vocabulary::PIMO::isDefinedBy()
{
    return s_pimo()->pimo_isDefinedBy;
}

QUrl Nepomuk::Vocabulary::PIMO::isLocationOf()
{
    return s_pimo()->pimo_isLocationOf;
}

QUrl Nepomuk::Vocabulary::PIMO::isOrganizationMemberOf()
{
    return s_pimo()->pimo_isOrganizationMemberOf;
}

QUrl Nepomuk::Vocabulary::PIMO::isRelated()
{
    return s_pimo()->pimo_isRelated;
}

QUrl Nepomuk::Vocabulary::PIMO::isTopicOf()
{
    return s_pimo()->pimo_isTopicOf;
}

QUrl Nepomuk::Vocabulary::PIMO::isWriteable()
{
    return s_pimo()->pimo_isWriteable;
}

QUrl Nepomuk::Vocabulary::PIMO::locatedWithin()
{
    return s_pimo()->pimo_locatedWithin;
}

QUrl Nepomuk::Vocabulary::PIMO::objectProperty()
{
    return s_pimo()->pimo_objectProperty;
}

QUrl Nepomuk::Vocabulary::PIMO::occurrence()
{
    return s_pimo()->pimo_occurrence;
}

QUrl Nepomuk::Vocabulary::PIMO::organization()
{
    return s_pimo()->pimo_organization;
}

QUrl Nepomuk::Vocabulary::PIMO::partOf()
{
    return s_pimo()->pimo_partOf;
}

QUrl Nepomuk::Vocabulary::PIMO::referencingOccurrence()
{
    return s_pimo()->pimo_referencingOccurrence;
}

QUrl Nepomuk::Vocabulary::PIMO::roleContext()
{
    return s_pimo()->pimo_roleContext;
}

QUrl Nepomuk::Vocabulary::PIMO::roleHolder()
{
    return s_pimo()->pimo_roleHolder;
}

QUrl Nepomuk::Vocabulary::PIMO::subTopic()
{
    return s_pimo()->pimo_subTopic;
}

QUrl Nepomuk::Vocabulary::PIMO::superTopic()
{
    return s_pimo()->pimo_superTopic;
}

QUrl Nepomuk::Vocabulary::PIMO::taskDueTime()
{
    return s_pimo()->pimo_taskDueTime;
}
